In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/competitions/playground-series-s5e12/sample_submission.csv
/kaggle/input/competitions/playground-series-s5e12/train.csv
/kaggle/input/competitions/playground-series-s5e12/test.csv

In [2]:
X_test=pd.read_csv('/kaggle/input/competitions/playground-series-s5e12/test.csv')
X_train=pd.read_csv('/kaggle/input/competitions/playground-series-s5e12/train.csv')

In [3]:
X_train.head(5)

,id,age,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,sleep_hours_per_day,screen_time_hours_per_day,bmi,waist_to_hip_ratio,systolic_bp,...,gender,ethnicity,education_level,income_level,smoking_status,employment_status,family_history_diabetes,hypertension_history,cardiovascular_history,diagnosed_diabetes
0,0,31,1,45,7.7,6.8,6.1,33.4,0.93,112,...,Female,Hispanic,Highschool,Lower-Middle,Current,Employed,0,0,0,1.0
1,1,50,2,73,5.7,6.5,5.8,23.8,0.83,120,...,Female,White,Highschool,Upper-Middle,Never,Employed,0,0,0,1.0
2,2,32,3,158,8.5,7.4,9.1,24.1,0.83,95,...,Male,Hispanic,Highschool,Lower-Middle,Never,Retired,0,0,0,0.0
3,3,54,3,77,4.6,7.0,9.2,26.6,0.83,121,...,Female,White,Highschool,Lower-Middle,Current,Employed,0,1,0,1.0
4,4,54,1,55,5.7,6.2,5.1,28.8,0.90,108,...,Male,White,Highschool,Upper-Middle,Never,Retired,0,1,0,1.0

In [4]:
test_id=X_test['id']

In [5]:
X_train.columns

Index(['id', 'age', 'alcohol_consumption_per_week',
       'physical_activity_minutes_per_week', 'diet_score',
       'sleep_hours_per_day', 'screen_time_hours_per_day', 'bmi',
       'waist_to_hip_ratio', 'systolic_bp', 'diastolic_bp', 'heart_rate',
       'cholesterol_total', 'hdl_cholesterol', 'ldl_cholesterol',
       'triglycerides', 'gender', 'ethnicity', 'education_level',
       'income_level', 'smoking_status', 'employment_status',
       'family_history_diabetes', 'hypertension_history',
       'cardiovascular_history', 'diagnosed_diabetes'],
      dtype='object')

In [6]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700000 entries, 0 to 699999
Data columns (total 26 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   id                                  700000 non-null  int64
 1   age                                 700000 non-null  int64
 2   alcohol_consumption_per_week        700000 non-null  int64
 3   physical_activity_minutes_per_week  700000 non-null  int64
 4   diet_score                          700000 non-null  float64
 5   sleep_hours_per_day                 700000 non-null  float64
 6   screen_time_hours_per_day           700000 non-null  float64
 7   bmi                                 700000 non-null  float64
 8   waist_to_hip_ratio                  700000 non-null  float64
 9   systolic_bp                         700000 non-null  int64
 10  diastolic_bp                        700000 non-null  int64
 11  heart_rate                          700000 non-null  int64
 12  cholesterol_total                   700000 non-null  int64
 13  hdl_cholesterol                     700000 non-null  int64
 14  ldl_cholesterol                     700000 non-null  int64
 15  triglycerides                       700000 non-null  int64
 16  gender                              700000 non-null  object
 17  ethnicity                           700000 non-null  object
 18  education_level                     700000 non-null  object
 19  income_level                        700000 non-null  object
 20  smoking_status                      700000 non-null  object
 21  employment_status                   700000 non-null  object
 22  family_history_diabetes             700000 non-null  int64
 23  hypertension_history                700000 non-null  int64
 24  cardiovascular_history              700000 non-null  int64
 25  diagnosed_diabetes                  700000 non-null  float64
dtypes: float64(6), int64(14), object(6)
memory usage: 138.9+ MB

In [7]:
X_train.duplicated().sum()

np.int64(0)

In [8]:
y_train=X_train['diagnosed_diabetes']
X_train.drop(columns=['diagnosed_diabetes'],inplace=True)

In [9]:
y_train.head()

0    1.0
1    1.0
2    0.0
3    1.0
4    1.0
Name: diagnosed_diabetes, dtype: float64

In [10]:
colu=['gender', 'ethnicity', 'education_level',
       'income_level', 'smoking_status', 'employment_status']
for col in colu:
    print('x_Train : ',X_train[col].unique())
    print('-'*50)

x_Train :  ['Female' 'Male' 'Other']
--------------------------------------------------
x_Train :  ['Hispanic' 'White' 'Asian' 'Black' 'Other']
--------------------------------------------------
x_Train :  ['Highschool' 'Graduate' 'Postgraduate' 'No formal']
--------------------------------------------------
x_Train :  ['Lower-Middle' 'Upper-Middle' 'Low' 'Middle' 'High']
--------------------------------------------------
x_Train :  ['Current' 'Never' 'Former']
--------------------------------------------------
x_Train :  ['Employed' 'Retired' 'Student' 'Unemployed']
--------------------------------------------------

In [11]:
from sklearn.preprocessing import OneHotEncoder
enc=OneHotEncoder(handle_unknown='ignore',sparse_output=False).set_output(
        transform='pandas'
   )
train_encoded=enc.fit_transform(X_train[colu])
test_encoded=enc.transform(X_test[colu])

X_train=pd.concat([X_train.drop(columns=colu),train_encoded],axis=1)
X_test=pd.concat([X_test.drop(columns=colu),test_encoded],axis=1)

In [12]:
# """
# 'gender', 'ethnicity', 'education_level',
#        'income_level', 'smoking_status', 'employment_status',
#        'family_history_diabetes'

# """


# cols=['gender', 'ethnicity', 'education_level',
#        'income_level', 'smoking_status', 'employment_status']
# for col in cols:
#     print(x_train[col].unique())

In [13]:
# for col in cols:
#     print(col)

In [14]:
# from sklearn.preprocessing import LabelEncoder
# enc_={}
# for col in cols:
#     enc=LabelEncoder()
#     x_train[col]=enc.fit_transform(x_train[col])
#     x_test[col]=enc.transform(x_test[col])

In [15]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700000 entries, 0 to 699999
Data columns (total 43 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   id                                  700000 non-null  int64
 1   age                                 700000 non-null  int64
 2   alcohol_consumption_per_week        700000 non-null  int64
 3   physical_activity_minutes_per_week  700000 non-null  int64
 4   diet_score                          700000 non-null  float64
 5   sleep_hours_per_day                 700000 non-null  float64
 6   screen_time_hours_per_day           700000 non-null  float64
 7   bmi                                 700000 non-null  float64
 8   waist_to_hip_ratio                  700000 non-null  float64
 9   systolic_bp                         700000 non-null  int64
 10  diastolic_bp                        700000 non-null  int64
 11  heart_rate                          700000 non-null  int64
 12  cholesterol_total                   700000 non-null  int64
 13  hdl_cholesterol                     700000 non-null  int64
 14  ldl_cholesterol                     700000 non-null  int64
 15  triglycerides                       700000 non-null  int64
 16  family_history_diabetes             700000 non-null  int64
 17  hypertension_history                700000 non-null  int64
 18  cardiovascular_history              700000 non-null  int64
 19  gender_Female                       700000 non-null  float64
 20  gender_Male                         700000 non-null  float64
 21  gender_Other                        700000 non-null  float64
 22  ethnicity_Asian                     700000 non-null  float64
 23  ethnicity_Black                     700000 non-null  float64
 24  ethnicity_Hispanic                  700000 non-null  float64
 25  ethnicity_Other                     700000 non-null  float64
 26  ethnicity_White                     700000 non-null  float64
 27  education_level_Graduate            700000 non-null  float64
 28  education_level_Highschool          700000 non-null  float64
 29  education_level_No formal           700000 non-null  float64
 30  education_level_Postgraduate        700000 non-null  float64
 31  income_level_High                   700000 non-null  float64
 32  income_level_Low                    700000 non-null  float64
 33  income_level_Lower-Middle           700000 non-null  float64
 34  income_level_Middle                 700000 non-null  float64
 35  income_level_Upper-Middle           700000 non-null  float64
 36  smoking_status_Current              700000 non-null  float64
 37  smoking_status_Former               700000 non-null  float64
 38  smoking_status_Never                700000 non-null  float64
 39  employment_status_Employed          700000 non-null  float64
 40  employment_status_Retired           700000 non-null  float64
 41  employment_status_Student           700000 non-null  float64
 42  employment_status_Unemployed        700000 non-null  float64
dtypes: float64(29), int64(14)
memory usage: 229.6 MB

In [16]:
X_train.drop(columns=['id'],inplace=True)
X_test.drop(columns=['id'],inplace=True)

In [17]:
X_train.shape

(700000, 42)

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_temp,y_train,y_temp=train_test_split(X_train,
                                                y_train,
                                                random_state=42,
                                                test_size=0.4,
                                                stratify=y_train)
x_test,x_cv,y_test,y_cv=train_test_split(x_temp,y_temp,
                                         random_state=42,
                                            test_size=0.5,
                                            stratify=y_temp)

In [19]:
def create_features(X):
    import numpy as np

    X = X.copy()

    X['bp_ratio'] = X['systolic_bp'] / (X['diastolic_bp'] + 1)
    X['activity_per_age'] = X['physical_activity_minutes_per_week'] / (X['age'] + 1)

    X['obese'] = (X['bmi'] > 30).astype(int)
    X['high_bp'] = (X['systolic_bp'] > 140).astype(int)
    X['low_activity'] = (X['physical_activity_minutes_per_week'] < 150).astype(int)
    X['poor_sleep'] = (X['sleep_hours_per_day'] < 6).astype(int)

    X['high_risk'] = (
        (X['obese']) &
        (X['high_bp']) &
        (X['low_activity'])
    ).astype(int)

    X['chol_ratio'] = X['ldl_cholesterol'] / (X['hdl_cholesterol'] + 1)
    X['total_hdl_ratio'] = X['cholesterol_total'] / (X['hdl_cholesterol'] + 1)

    # X['genetic_risk'] = X['family_history_diabetes'] * X['bmi']

    X['bmi_age'] = X['bmi'] * X['age']

    X['bp_chol_product'] = X['systolic_bp'] * X['cholesterol_total']

    X['lifestyle_score'] = (
        X['smoking_status_Current']*3 +
        X['low_activity']*2 +
        X['poor_sleep'] +
        X['obese']*2
    )

    X['old_age'] = (X['age'] > 50).astype(int)

    X['bp_genetic'] = X['systolic_bp'] * X['family_history_diabetes']
    X['bmi_genetic'] = X['bmi'] * X['family_history_diabetes']

    X['metabolic_score'] = (
    X['bmi'] +
    X['systolic_bp'] +
    X['cholesterol_total'] +
    X['triglycerides']
    )
    X['lifestyle_risk'] = (
    X['smoking_status_Current']*3 +
    X['low_activity']*2 +
    X['poor_sleep'] +
    X['screen_time_hours_per_day']
    )
    X['body_stress'] = (
    X['heart_rate'] +
    X['systolic_bp'] +
    X['bmi']
    )
    X['lipid_risk'] = (
    X['ldl_cholesterol'] +
    X['triglycerides'] -
    X['hdl_cholesterol']
)

    return X

In [20]:
x_train = create_features(x_train)
x_cv = create_features(x_cv)
x_test = create_features(x_test)

In [21]:
X_test=create_features(X_test)

In [22]:
x_train.shape

(420000, 61)

In [23]:
X_test.shape

(300000, 61)

In [24]:
print('x_train.shape',x_train.shape)
print('x_test.shape',x_test.shape)
print('x_cv.shape',x_cv.shape)

x_train.shape (420000, 61)
x_test.shape (140000, 61)
x_cv.shape (140000, 61)

In [25]:
print('y_train.shape',y_train.shape)
print('y_test.shape',y_test.shape)
print('y_cv.shape',y_cv.shape)

y_train.shape (420000,)
y_test.shape (140000,)
y_cv.shape (140000,)

In [26]:
def min_max(x,col):
    for c in col:
        print(c)
        print('max : ',x[c].max())
        print('min : ' ,x[c].min())
        print('-'*50)

In [27]:
x_train.columns

Index(['age', 'alcohol_consumption_per_week',
       'physical_activity_minutes_per_week', 'diet_score',
       'sleep_hours_per_day', 'screen_time_hours_per_day', 'bmi',
       'waist_to_hip_ratio', 'systolic_bp', 'diastolic_bp', 'heart_rate',
       'cholesterol_total', 'hdl_cholesterol', 'ldl_cholesterol',
       'triglycerides', 'family_history_diabetes', 'hypertension_history',
       'cardiovascular_history', 'gender_Female', 'gender_Male',
       'gender_Other', 'ethnicity_Asian', 'ethnicity_Black',
       'ethnicity_Hispanic', 'ethnicity_Other', 'ethnicity_White',
       'education_level_Graduate', 'education_level_Highschool',
       'education_level_No formal', 'education_level_Postgraduate',
       'income_level_High', 'income_level_Low', 'income_level_Lower-Middle',
       'income_level_Middle', 'income_level_Upper-Middle',
       'smoking_status_Current', 'smoking_status_Former',
       'smoking_status_Never', 'employment_status_Employed',
       'employment_status_Retired', 'employment_status_Student',
       'employment_status_Unemployed', 'bp_ratio', 'activity_per_age', 'obese',
       'high_bp', 'low_activity', 'poor_sleep', 'high_risk', 'chol_ratio',
       'total_hdl_ratio', 'bmi_age', 'bp_chol_product', 'lifestyle_score',
       'old_age', 'bp_genetic', 'bmi_genetic', 'metabolic_score',
       'lifestyle_risk', 'body_stress', 'lipid_risk'],
      dtype='object')

In [28]:
col=['age', 'alcohol_consumption_per_week',
       'physical_activity_minutes_per_week', 'diet_score',
       'sleep_hours_per_day', 'screen_time_hours_per_day', 'bmi',
       'waist_to_hip_ratio', 'systolic_bp', 'diastolic_bp', 'heart_rate',
       'cholesterol_total', 'hdl_cholesterol', 'ldl_cholesterol',
       'triglycerides', 'family_history_diabetes', 'hypertension_history',
       'cardiovascular_history', 'gender_Female', 'gender_Male',
       'gender_Other', 'ethnicity_Asian', 'ethnicity_Black',
       'ethnicity_Hispanic', 'ethnicity_Other', 'ethnicity_White',
       'education_level_Graduate', 'education_level_Highschool',
       'education_level_No formal', 'education_level_Postgraduate',
       'income_level_High', 'income_level_Low', 'income_level_Lower-Middle',
       'income_level_Middle', 'income_level_Upper-Middle',
       'smoking_status_Current', 'smoking_status_Former',
       'smoking_status_Never', 'employment_status_Employed',
       'employment_status_Retired', 'employment_status_Student',
       'employment_status_Unemployed']
min_max(x_train,col)

age
max :  89
min :  19
--------------------------------------------------
alcohol_consumption_per_week
max :  8
min :  1
--------------------------------------------------
physical_activity_minutes_per_week
max :  705
min :  1
--------------------------------------------------
diet_score
max :  9.9
min :  0.1
--------------------------------------------------
sleep_hours_per_day
max :  9.9
min :  3.1
--------------------------------------------------
screen_time_hours_per_day
max :  16.5
min :  0.6
--------------------------------------------------
bmi
max :  38.4
min :  15.1
--------------------------------------------------
waist_to_hip_ratio
max :  1.05
min :  0.68
--------------------------------------------------
systolic_bp
max :  163
min :  91
--------------------------------------------------
diastolic_bp
max :  104
min :  51
--------------------------------------------------
heart_rate
max :  99
min :  42
--------------------------------------------------
cholesterol_total
max :  289
min :  121
--------------------------------------------------
hdl_cholesterol
max :  90
min :  21
--------------------------------------------------
ldl_cholesterol
max :  205
min :  51
--------------------------------------------------
triglycerides
max :  290
min :  31
--------------------------------------------------
family_history_diabetes
max :  1
min :  0
--------------------------------------------------
hypertension_history
max :  1
min :  0
--------------------------------------------------
cardiovascular_history
max :  1
min :  0
--------------------------------------------------
gender_Female
max :  1.0
min :  0.0
--------------------------------------------------
gender_Male
max :  1.0
min :  0.0
--------------------------------------------------
gender_Other
max :  1.0
min :  0.0
--------------------------------------------------
ethnicity_Asian
max :  1.0
min :  0.0
--------------------------------------------------
ethnicity_Black
max :  1.0
min :  0.0
--------------------------------------------------
ethnicity_Hispanic
max :  1.0
min :  0.0
--------------------------------------------------
ethnicity_Other
max :  1.0
min :  0.0
--------------------------------------------------
ethnicity_White
max :  1.0
min :  0.0
--------------------------------------------------
education_level_Graduate
max :  1.0
min :  0.0
--------------------------------------------------
education_level_Highschool
max :  1.0
min :  0.0
--------------------------------------------------
education_level_No formal
max :  1.0
min :  0.0
--------------------------------------------------
education_level_Postgraduate
max :  1.0
min :  0.0
--------------------------------------------------
income_level_High
max :  1.0
min :  0.0
--------------------------------------------------
income_level_Low
max :  1.0
min :  0.0
--------------------------------------------------
income_level_Lower-Middle
max :  1.0
min :  0.0
--------------------------------------------------
income_level_Middle
max :  1.0
min :  0.0
--------------------------------------------------
income_level_Upper-Middle
max :  1.0
min :  0.0
--------------------------------------------------
smoking_status_Current
max :  1.0
min :  0.0
--------------------------------------------------
smoking_status_Former
max :  1.0
min :  0.0
--------------------------------------------------
smoking_status_Never
max :  1.0
min :  0.0
--------------------------------------------------
employment_status_Employed
max :  1.0
min :  0.0
--------------------------------------------------
employment_status_Retired
max :  1.0
min :  0.0
--------------------------------------------------
employment_status_Student
max :  1.0
min :  0.0
--------------------------------------------------
employment_status_Unemployed
max :  1.0
min :  0.0
--------------------------------------------------

In [29]:

'''
one hot encoding on 'gender', 'ethnicity', 'education_level',
       'income_level', 'smoking_status', 'employment_status',
       'family_history_diabetes'

standardscalar for logistic regression 
no standardscalar or anything for tress based

'''

"\none hot encoding on 'gender', 'ethnicity', 'education_level',\n       'income_level', 'smoking_status', 'employment_status',\n       'family_history_diabetes'\n\nstandardscalar for logistic regression \nno standardscalar or anything for tress based\n\n"

In [30]:
from xgboost import XGBClassifier
model_xgb = model_xgb = XGBClassifier(
    n_estimators=600,
    max_depth=7,
    learning_rate=0.03,
    subsample=0.8,
    colsample_bytree=0.8,
    gamma=1
)
model_xgb.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=1, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.03, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=7,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=600,
              n_jobs=None, num_parallel_tree=None, ...)

In [31]:
probs = model_xgb.predict_proba(x_cv)[:, 1]

thresholds = [0.5, 0.55, 0.6, 0.65, 0.7]

from sklearn.metrics import confusion_matrix,accuracy_score

for t in thresholds:
    pred_cv = (probs > t).astype(int)
    
    print(f"Threshold: {t}")
    print(confusion_matrix(y_cv, pred_cv))
    print('accuracy : ',accuracy_score(y_cv, pred_cv))
    print()

Threshold: 0.5
[[21686 31053]
 [13359 73902]]
accuracy :  0.6827714285714286

Threshold: 0.55
[[28066 24673]
 [20283 66978]]
accuracy :  0.6788857142857143

Threshold: 0.6
[[34187 18552]
 [28567 58694]]
accuracy :  0.6634357142857142

Threshold: 0.65
[[39746 12993]
 [38076 49185]]
accuracy :  0.6352214285714286

Threshold: 0.7
[[44309  8430]
 [48006 39255]]
accuracy :  0.5968857142857142

In [32]:
pred_test=model_xgb.predict(x_test)

In [33]:
from sklearn.metrics import accuracy_score
print('test - > ',accuracy_score(y_test,pred_test))
print('cross-validation - > ',accuracy_score(y_cv,pred_cv))
# print('training - > ',accuracy_score(y_train,pred_train))

test - >  0.6802142857142857
cross-validation - >  0.5968857142857142

In [34]:
from sklearn.metrics import confusion_matrix

print('test - > ')
print(confusion_matrix(y_test,pred_test))
print('cross-validation - > ')
print(confusion_matrix(y_cv,pred_cv))
print('training - > ')
# print(confusion_matrix(y_train,pred_train))

test - >
[[21563 31175]
 [13595 73667]]
cross-validation - >
[[44309  8430]
 [48006 39255]]
training - >

In [35]:
print('test : ',(y_test==1).sum())
print('test : ',(y_test==0).sum())
print('-'*50)
print('cv : ',(y_cv==1).sum())
print('cv : ',(y_cv==0).sum())
print('-'*50)
print('train : ',(y_train==1).sum())
print('train : ',(y_train==0).sum()),

test :  87262
test :  52738
--------------------------------------------------
cv :  87261
cv :  52739
--------------------------------------------------
train :  261784
train :  158216

(None,)

In [36]:
X_train.columns

Index(['age', 'alcohol_consumption_per_week',
       'physical_activity_minutes_per_week', 'diet_score',
       'sleep_hours_per_day', 'screen_time_hours_per_day', 'bmi',
       'waist_to_hip_ratio', 'systolic_bp', 'diastolic_bp', 'heart_rate',
       'cholesterol_total', 'hdl_cholesterol', 'ldl_cholesterol',
       'triglycerides', 'family_history_diabetes', 'hypertension_history',
       'cardiovascular_history', 'gender_Female', 'gender_Male',
       'gender_Other', 'ethnicity_Asian', 'ethnicity_Black',
       'ethnicity_Hispanic', 'ethnicity_Other', 'ethnicity_White',
       'education_level_Graduate', 'education_level_Highschool',
       'education_level_No formal', 'education_level_Postgraduate',
       'income_level_High', 'income_level_Low', 'income_level_Lower-Middle',
       'income_level_Middle', 'income_level_Upper-Middle',
       'smoking_status_Current', 'smoking_status_Former',
       'smoking_status_Never', 'employment_status_Employed',
       'employment_status_Retired', 'employment_status_Student',
       'employment_status_Unemployed'],
      dtype='object')

In [37]:
import pandas as pd

importance = pd.Series(model_xgb.feature_importances_, index=x_train.columns)
print(importance.sort_values(ascending=False).head(20))

family_history_diabetes               0.361339
bp_genetic                            0.203036
bmi_genetic                           0.109672
activity_per_age                      0.048836
low_activity                          0.018960
bmi_age                               0.018598
physical_activity_minutes_per_week    0.016612
lipid_risk                            0.009143
age                                   0.008572
obese                                 0.007829
triglycerides                         0.007436
metabolic_score                       0.007250
old_age                               0.007087
diet_score                            0.004802
bmi                                   0.004795
cardiovascular_history                0.004705
heart_rate                            0.004701
waist_to_hip_ratio                    0.004387
cholesterol_total                     0.004299
hdl_cholesterol                       0.004189
dtype: float32

In [38]:
cols=['age', 'alcohol_consumption_per_week',
       'physical_activity_minutes_per_week', 'diet_score',
       'sleep_hours_per_day', 'screen_time_hours_per_day', 'bmi',
       'waist_to_hip_ratio', 'systolic_bp', 'diastolic_bp', 'heart_rate',
       'cholesterol_total', 'hdl_cholesterol', 'ldl_cholesterol',
       'triglycerides']
from sklearn.preprocessing import StandardScaler
for col in cols:
    scal=StandardScaler()
    x_train[col]=scal.fit_transform(x_train[[col]])
    x_cv[col]=scal.transform(x_cv[[col]])
    x_test[col]=scal.transform(x_test[[col]])

In [39]:
x_train[:5]

,age,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,sleep_hours_per_day,screen_time_hours_per_day,bmi,waist_to_hip_ratio,systolic_bp,diastolic_bp,...,bmi_age,bp_chol_product,lifestyle_score,old_age,bp_genetic,bmi_genetic,metabolic_score,lifestyle_risk,body_stress,lipid_risk
620341,2.027136,2.796509,-1.313374,-1.818851,-1.221325,-1.190981,0.812309,0.295521,0.154161,-0.797072,...,2086.8,22302,3.0,1,0,0.0,504.2,6.6,209.2,235
69813,2.027136,-1.023290,-0.902868,-2.228660,-0.113455,-0.301608,0.427965,1.348830,1.335133,1.986943,...,2005.4,27379,2.0,1,0,0.0,467.1,7.4,224.1,170
490270,1.169677,-1.023290,-0.511909,0.981514,0.108119,-1.388619,0.008681,0.558848,1.607665,0.228618,...,1657.6,26666,2.0,1,0,0.0,467.9,5.2,228.9,174
531879,0.655202,0.886610,1.853391,-1.067533,-0.999751,-0.252198,-0.585304,-0.494461,-0.935968,0.375145,...,1403.6,16324,0.0,1,106,24.2,394.2,5.5,200.2,105
49440,0.140727,-1.023290,-0.042758,0.981514,1.548349,0.439537,-1.493753,-0.757788,-0.390904,0.668199,...,1123.2,18256,2.0,1,112,21.6,437.6,8.9,200.6,166

In [40]:
from sklearn.linear_model import LogisticRegression
log_reg=LogisticRegression()
log_reg.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [41]:
pred_cv_log=log_reg.predict(x_cv)
pred_train_log=log_reg.predict(x_train)
pred_test_log=log_reg.predict(x_test)

In [42]:
print(accuracy_score(y_cv,pred_cv_log))
print(accuracy_score(y_train,pred_train_log))
print(accuracy_score(y_test,pred_test_log))

0.6586142857142857
0.6574595238095238
0.6568357142857143

In [43]:
print(confusion_matrix(y_cv,pred_cv_log))
print('\n')
print(confusion_matrix(y_train,pred_train_log))
print('\n')
print(confusion_matrix(y_test,pred_test_log))

[[17357 35382]
 [12412 74849]]


[[ 52086 106130]
 [ 37737 224047]]


[[17243 35495]
 [12548 74714]]

In [44]:
# probabilities
probs = model_xgb.predict_proba(X_test)[:, 1]

# threshold
final_pred = (probs > 0.55).astype(int)

# load sample submission
submission = pd.read_csv('/kaggle/input/competitions/playground-series-s5e12/sample_submission.csv')

# replace predictions
submission['diagnosed_diabetes'] = final_pred

# save
submission.to_csv('submission.csv', index=False)