<a href="https://colab.research.google.com/github/DeepanshuSharma1607/project/blob/main/Spaceship_Titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1197]:
import numpy as np
import pandas as pd

In [1198]:
df=pd.read_csv("/content/train.csv")
df_test=pd.read_csv("/content/test.csv")
df.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [1199]:
df_test.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
1,0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
2,0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
3,0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
4,0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez

In [1200]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   object
 4   Destination   8511 non-null   object
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB

In [1201]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   4277 non-null   object
 1   HomePlanet    4190 non-null   object
 2   CryoSleep     4184 non-null   object
 3   Cabin         4177 non-null   object
 4   Destination   4185 non-null   object
 5   Age           4186 non-null   float64
 6   VIP           4184 non-null   object
 7   RoomService   4195 non-null   float64
 8   FoodCourt     4171 non-null   float64
 9   ShoppingMall  4179 non-null   float64
 10  Spa           4176 non-null   float64
 11  VRDeck        4197 non-null   float64
 12  Name          4183 non-null   object
dtypes: float64(6), object(7)
memory usage: 434.5+ KB

In [1202]:
def uni(x):
    print(x.unique())

In [1203]:
for i in df.columns:
    if df[i].dtype=='object':
        print(i)
        uni(df[i])
        print(df[i].nunique())
        print('*'*50)

PassengerId
['0001_01' '0002_01' '0003_01' ... '9279_01' '9280_01' '9280_02']
8693
**************************************************
HomePlanet
['Europa' 'Earth' 'Mars' nan]
3
**************************************************
CryoSleep
[False True nan]
2
**************************************************
Cabin
['B/0/P' 'F/0/S' 'A/0/S' ... 'G/1499/S' 'G/1500/S' 'E/608/S']
6560
**************************************************
Destination
['TRAPPIST-1e' 'PSO J318.5-22' '55 Cancri e' nan]
3
**************************************************
VIP
[False True nan]
2
**************************************************
Name
['Maham Ofracculy' 'Juanna Vines' 'Altark Susent' ... 'Fayey Connon'
 'Celeon Hontichre' 'Propsh Hontichre']
8473
**************************************************

In [1204]:
for i in df_test.columns:
    if df_test[i].dtype=='object':
        print(i)
        uni(df_test[i])
        print(df_test[i].nunique())
        print('*'*50)

PassengerId
['0013_01' '0018_01' '0019_01' ... '9271_01' '9273_01' '9277_01']
4277
**************************************************
HomePlanet
['Earth' 'Europa' 'Mars' nan]
3
**************************************************
CryoSleep
[True False nan]
2
**************************************************
Cabin
['G/3/S' 'F/4/S' 'C/0/S' ... 'D/296/P' 'D/297/P' 'G/1498/S']
3265
**************************************************
Destination
['TRAPPIST-1e' '55 Cancri e' 'PSO J318.5-22' nan]
3
**************************************************
VIP
[False nan True]
2
**************************************************
Name
['Nelly Carsoning' 'Lerome Peckers' 'Sabih Unhearfus' ... 'Jayrin Pore'
 'Kitakan Conale' 'Lilace Leonzaley']
4176
**************************************************

In [1205]:
df[['Deck','CabinNum','Side']] = df['Cabin'].str.split('/', expand=True)
df.drop(columns=['Cabin'], inplace=True)
df['TotalSpend'] = df[['RoomService','FoodCourt','ShoppingMall','Spa','VRDeck']].sum(axis=1)
df.loc[df['CryoSleep']==True, ['RoomService','FoodCourt','ShoppingMall','Spa','VRDeck']] = 0

In [1206]:
df_test[['Deck', 'CabinNum', 'Side']] = df_test['Cabin'].str.split('/', expand=True)
df_test.drop(columns=['Cabin'], inplace=True)
df_test['TotalSpend'] = df_test[['RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']].sum(axis=1)

df_test.loc[df_test['CryoSleep'] == True, ['RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']] = 0

In [1207]:
df['VIP'] = df['VIP'].fillna(False)
df_test['VIP'] = df_test['VIP'].fillna(False)

/tmp/ipykernel_5466/3594162684.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['VIP'] = df['VIP'].fillna(False)
/tmp/ipykernel_5466/3594162684.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_test['VIP'] = df_test['VIP'].fillna(False)

In [1208]:
print(df.duplicated().sum())
print(df_test.duplicated().sum())

0
0

In [1209]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8476 non-null   object
 3   Destination   8511 non-null   object
 4   Age           8514 non-null   float64
 5   VIP           8693 non-null   bool
 6   RoomService   8580 non-null   float64
 7   FoodCourt     8580 non-null   float64
 8   ShoppingMall  8581 non-null   float64
 9   Spa           8575 non-null   float64
 10  VRDeck        8567 non-null   float64
 11  Name          8493 non-null   object
 12  Transported   8693 non-null   bool
 13  Deck          8494 non-null   object
 14  CabinNum      8494 non-null   object
 15  Side          8494 non-null   object
 16  TotalSpend    8693 non-null   float64
dtypes: bool(2), float64(7), object(8)
memory usage: 1.0+ MB

In [1210]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   4277 non-null   object
 1   HomePlanet    4190 non-null   object
 2   CryoSleep     4184 non-null   object
 3   Destination   4185 non-null   object
 4   Age           4186 non-null   float64
 5   VIP           4277 non-null   bool
 6   RoomService   4220 non-null   float64
 7   FoodCourt     4210 non-null   float64
 8   ShoppingMall  4214 non-null   float64
 9   Spa           4218 non-null   float64
 10  VRDeck        4226 non-null   float64
 11  Name          4183 non-null   object
 12  Deck          4177 non-null   object
 13  CabinNum      4177 non-null   object
 14  Side          4177 non-null   object
 15  TotalSpend    4277 non-null   float64
dtypes: bool(1), float64(7), object(8)
memory usage: 505.5+ KB

In [1211]:
numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns
object_cols = df.select_dtypes(include=['object']).columns

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].mean())

for col in object_cols:
    df[col] = df[col].fillna("Unknown")

In [1212]:
numeric_cols = df_test.select_dtypes(include=['float64', 'int64']).columns
object_cols = df_test.select_dtypes(include=['object']).columns

for col in numeric_cols:
    df_test[col] = df_test[col].fillna(df_test[col].median())

for col in object_cols:
    df_test[col] = df_test[col].fillna("Unknown")

In [1213]:
df=df.drop(columns=['PassengerId','Name'])
df.shape,y.shape

((8693, 15), (8693,))

In [1214]:
df_test=df_test.drop(columns=['PassengerId','Name'])
df_test.shape

(4277, 14)

In [1215]:
df['CabinNum'] = pd.to_numeric(df['CabinNum'], errors='coerce')

df['CabinNum'] = df.groupby('Deck')['CabinNum'].transform(
    lambda x: x.fillna(x.median())
)
df['CabinNum'] = df['CabinNum'].fillna(df['CabinNum'].median())

In [1216]:
df['CabinZone'], bin_edges = pd.cut(df['CabinNum'], bins=6, labels=[1,2,3,4,5,6], retbins=True)
df['CabinZone'] = df['CabinZone'].astype(int)

In [1217]:
df_test['CabinNum'] = pd.to_numeric(df_test['CabinNum'], errors='coerce')

df_test['CabinNum'] = df_test.groupby('Deck')['CabinNum'].transform(
    lambda x: x.fillna(x.median())
)
df_test['CabinNum'] = df_test['CabinNum'].fillna(df_test['CabinNum'].median())

In [1218]:
df_test['CabinZone'] = pd.cut(df_test['CabinNum'], bins=bin_edges, labels=[1,2,3,4,5,6]).fillna(1).astype(int)

In [1219]:
df = pd.get_dummies(df, columns=['HomePlanet', 'Destination', 'Deck', 'Side'])

In [1220]:
df_test = pd.get_dummies(df_test, columns=['HomePlanet', 'Destination', 'Deck', 'Side'])

In [1221]:
df['CryoSleep'] = df['CryoSleep'].astype(str).str.strip()

df.loc[(df['CryoSleep'] == 'Unknown') & (df['TotalSpend'] > 0), 'CryoSleep'] = 'False'
df.loc[(df['CryoSleep'] == 'Unknown') & (df['TotalSpend'] == 0), 'CryoSleep'] = 'True'
df['CryoSleep'] = df['CryoSleep'].map({'True': 1, 'False': 0})

print(df['CryoSleep'].value_counts())

CryoSleep
0    5558
1    3135
Name: count, dtype: int64

In [1222]:
df_test['CryoSleep'] = df_test['CryoSleep'].astype(str).str.strip()

df_test.loc[(df_test['CryoSleep'] == 'Unknown') & (df_test['TotalSpend'] > 0), 'CryoSleep'] = 'False'
df_test.loc[(df_test['CryoSleep'] == 'Unknown') & (df_test['TotalSpend'] == 0), 'CryoSleep'] = 'True'
df_test['CryoSleep'] = df_test['CryoSleep'].map({'True': 1, 'False': 0})

print(df_test['CryoSleep'].value_counts())

CryoSleep
0    2695
1    1582
Name: count, dtype: int64

In [1223]:
df_test['CryoSleep'] = df_test['CryoSleep'].fillna(0)

In [1224]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 32 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   CryoSleep                  8693 non-null   int64
 1   Age                        8693 non-null   float64
 2   VIP                        8693 non-null   bool
 3   RoomService                8693 non-null   float64
 4   FoodCourt                  8693 non-null   float64
 5   ShoppingMall               8693 non-null   float64
 6   Spa                        8693 non-null   float64
 7   VRDeck                     8693 non-null   float64
 8   Transported                8693 non-null   bool
 9   CabinNum                   8693 non-null   float64
 10  TotalSpend                 8693 non-null   float64
 11  CabinZone                  8693 non-null   int64
 12  HomePlanet_Earth           8693 non-null   bool
 13  HomePlanet_Europa          8693 non-null   bool
 14  HomePlanet_Mars            8693 non-null   bool
 15  HomePlanet_Unknown         8693 non-null   bool
 16  Destination_55 Cancri e    8693 non-null   bool
 17  Destination_PSO J318.5-22  8693 non-null   bool
 18  Destination_TRAPPIST-1e    8693 non-null   bool
 19  Destination_Unknown        8693 non-null   bool
 20  Deck_A                     8693 non-null   bool
 21  Deck_B                     8693 non-null   bool
 22  Deck_C                     8693 non-null   bool
 23  Deck_D                     8693 non-null   bool
 24  Deck_E                     8693 non-null   bool
 25  Deck_F                     8693 non-null   bool
 26  Deck_G                     8693 non-null   bool
 27  Deck_T                     8693 non-null   bool
 28  Deck_Unknown               8693 non-null   bool
 29  Side_P                     8693 non-null   bool
 30  Side_S                     8693 non-null   bool
 31  Side_Unknown               8693 non-null   bool
dtypes: bool(22), float64(8), int64(2)
memory usage: 866.0 KB

In [1225]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 31 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   CryoSleep                  4277 non-null   int64
 1   Age                        4277 non-null   float64
 2   VIP                        4277 non-null   bool
 3   RoomService                4277 non-null   float64
 4   FoodCourt                  4277 non-null   float64
 5   ShoppingMall               4277 non-null   float64
 6   Spa                        4277 non-null   float64
 7   VRDeck                     4277 non-null   float64
 8   CabinNum                   4277 non-null   float64
 9   TotalSpend                 4277 non-null   float64
 10  CabinZone                  4277 non-null   int64
 11  HomePlanet_Earth           4277 non-null   bool
 12  HomePlanet_Europa          4277 non-null   bool
 13  HomePlanet_Mars            4277 non-null   bool
 14  HomePlanet_Unknown         4277 non-null   bool
 15  Destination_55 Cancri e    4277 non-null   bool
 16  Destination_PSO J318.5-22  4277 non-null   bool
 17  Destination_TRAPPIST-1e    4277 non-null   bool
 18  Destination_Unknown        4277 non-null   bool
 19  Deck_A                     4277 non-null   bool
 20  Deck_B                     4277 non-null   bool
 21  Deck_C                     4277 non-null   bool
 22  Deck_D                     4277 non-null   bool
 23  Deck_E                     4277 non-null   bool
 24  Deck_F                     4277 non-null   bool
 25  Deck_G                     4277 non-null   bool
 26  Deck_T                     4277 non-null   bool
 27  Deck_Unknown               4277 non-null   bool
 28  Side_P                     4277 non-null   bool
 29  Side_S                     4277 non-null   bool
 30  Side_Unknown               4277 non-null   bool
dtypes: bool(21), float64(8), int64(2)
memory usage: 422.0 KB

In [1226]:
df.head()

,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,CabinNum,...,Deck_C,Deck_D,Deck_E,Deck_F,Deck_G,Deck_T,Deck_Unknown,Side_P,Side_S,Side_Unknown
0,0,39.0,False,0.0,0.0,0.0,0.0,0.0,False,0.0,...,False,False,False,False,False,False,False,True,False,False
1,0,24.0,False,109.0,9.0,25.0,549.0,44.0,True,0.0,...,False,False,False,True,False,False,False,False,True,False
2,0,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False,0.0,...,False,False,False,False,False,False,False,False,True,False
3,0,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False,0.0,...,False,False,False,False,False,False,False,False,True,False
4,0,16.0,False,303.0,70.0,151.0,565.0,2.0,True,1.0,...,False,False,False,True,False,False,False,False,True,False

In [1227]:
df_test

,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,CabinNum,TotalSpend,...,Deck_C,Deck_D,Deck_E,Deck_F,Deck_G,Deck_T,Deck_Unknown,Side_P,Side_S,Side_Unknown
0,1,27.0,False,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,False,False,False,False,True,False,False,False,True,False
1,0,19.0,False,0.0,9.0,0.0,2823.0,0.0,4.0,2832.0,...,False,False,False,True,False,False,False,False,True,False
2,1,31.0,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,True,False,False,False,False,False,False,False,True,False
3,0,38.0,False,0.0,6652.0,0.0,181.0,585.0,1.0,7418.0,...,True,False,False,False,False,False,False,False,True,False
4,0,20.0,False,10.0,0.0,635.0,0.0,0.0,5.0,645.0,...,False,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,1,34.0,False,0.0,0.0,0.0,0.0,0.0,1496.0,0.0,...,False,False,False,False,True,False,False,False,True,False
4273,0,42.0,False,0.0,847.0,17.0,10.0,144.0,442.0,1018.0,...,False,False,False,False,False,False,True,False,False,True
4274,1,26.0,False,0.0,0.0,0.0,0.0,0.0,296.0,0.0,...,False,True,False,False,False,False,False,True,False,False
4275,0,26.0,False,0.0,2680.0,0.0,0.0,523.0,297.0,3203.0,...,False,True,False,False,False,False,False,True,False,False
4276,1,43.0,False,0.0,0.0,0.0,0.0,0.0,1498.0,0.0,...,False,False,False,False,True,False,False,False,True,False

In [1228]:
bool_cols = df.select_dtypes(include=['bool']).columns
df[bool_cols] = df[bool_cols].astype(int)

bool_cols = df_test.select_dtypes(include=['bool']).columns
df_test[bool_cols] = df_test[bool_cols].astype(int)

In [1229]:
unknown_cols = [col for col in df.columns if 'Unknown' in col]
df.drop(columns=unknown_cols, inplace=True)

In [1230]:
unknown_cols = [col for col in df_test.columns if 'Unknown' in col]
df_test.drop(columns=unknown_cols, inplace=True)

In [1232]:
X = df.drop(columns=['Transported'])
y = df['Transported']
X_test = df_test.copy()

In [1233]:
missing_in_test = set(X.columns) - set(X_test.columns)
print("Missing in test:", missing_in_test)

extra_in_test = set(X_test.columns) - set(X.columns)
print("Extra in test:", extra_in_test)

Missing in test: set()
Extra in test: set()

In [1234]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

xgb_model = XGBClassifier(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    min_child_weight=3,
    reg_alpha=0.1,
    reg_lambda=1.0,
    random_state=42,
    eval_metric='logloss'
)

In [1235]:
from sklearn.model_selection import StratifiedKFold, cross_val_score

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
scores = cross_val_score(xgb_model, X, y, cv=cv, scoring='accuracy')
print(f"CV Accuracy: {scores.mean():.5f} ± {scores.std():.5f}")

CV Accuracy: 0.81054 ± 0.00908

In [1237]:
xgb_model.fit(X, y)

final_preds = xgb_model.predict(X_test)

submission = pd.DataFrame({
    "PassengerId": df_test_raw["PassengerId"],
    "Transported": final_preds.astype(bool)
})
submission.to_csv('__submission__.csv', index=False)
print("Submitted!")

Submitted!